### ISSUE TITLE
Support for Bamboo 5.12

### ISSUE THREAD

**Issue by psychomieze** [onepremise/gReview#35]
Hey,

will it be possible to use the plugin with Bamboo 5.12 or were there too many changes? 

Thx in advance,

Susi

**Comment by onepremise** [comment]
Hi Susi,

I haven't tested the latest release against 5.12. We just provided support for 5.8-5.10. We've had requests for ports to 5.11 and 5.12, but so for nobody has requested official support (provided funding) for us to port. We usually upgrade when there's a need internally or upon customer request. You are more than welcome to inquire regarding support if you need something right away. You are always welcome to make a pull request as well if you would like to provide the update. Otherwise, we usually cycle around the end of the year and upgrade internally and release.

**Comment by psychomieze** [comment]
Hey,

thanks for replying. We are an Open Source project so we know about funding needs ;) If you want you can contact me via email and send me a quote / how many funds you'd need to upgrade to 5.12.

Susi

**Comment by onepremise** [comment]
Hi Susi,

We appreciate the support. I'll forward along a quote via email. Let me know if you have any further questions. 

Thanks!

**Comment by marcostorto** [comment]
Hi, 

Do you have any plan to extend support to latest bamboo version? 
Thanks!

Marco

**Comment by jurek7** [comment]
@onepremise do you know if there was any changes that could break support in 5.12 ?

**Comment by onepremise** [comment]
Hi jurek7, I haven't tested a 5.12 deployment yet, so I can't really answer. I can say we've had some luck in the past deploying to the next release without having to update, but 5.10.3 to 5.12 might be to big of a jump. I would expect some minor regressions, but you are certainly welcome to try and let us know. You're welcome to inquire houghtonassociates.com for paid support at opensource@houghtonassociates.com if you need something immediately. Otherwise, we also accept pull requests if you would like to update the plugin to support 5.12 yourself.
